esphome:
  name: $dev_id
  platform: ESP32
  board: esp32dev
  comment: $dev_name

  # Include customized header files for TFT_eSPI, LVGL components and the demo UI
  includes:
    - common/lvgl/lv_conf.h
    - common/lvgl/awesome_extra_16.h
    - common/lvgl/awesome_extra_16.c
    - common/lvgl/LvglComponent.h

  # Dowload extra libraries for TFT_eSPI, LVGL and the demo UI
  libraries:
    - SPI
    - Wire
    - bodmer/tft_espi
    - lvgl/lvgl
    - git+https://github.com/aselectroworks/Arduino-FT6336U.git

  platformio_options:
    upload_speed: 921600
    build_flags:
      - "-D LV_CONF_INCLUDE_SIMPLE"
      - "-D LV_LVGL_H_INCLUDE_SIMPLE"
      - "-D LV_DEMO_CONF_INCLUDE_SIMPLE"
      - "-I src      ; for lv_conf.h"
      - "-D LV_MEM_SIZE=49152U           ; 48 kB lvgl memory"
      # The folowing defines will configure the TFT display driver, size and pins
      - "-D USER_SETUP_LOADED=1"
      - "-D ST7789_DRIVER=1"
      - "-D SUPPORT_TRANSACTIONS ; Default on ESP32"
      - "-D TFT_WIDTH=240"
      - "-D TFT_HEIGHT=320"
      - "-D TFT_ROTATION=2 ; Rotate 180"
      - "-D TFT_MISO=25"
      - "-D TFT_MOSI=23"
      - "-D TFT_SCLK=19"
      - "-D TFT_RST=18"
      - "-D TFT_DC=21"
      - "-D TFT_CS=22"
      - "-D TFT_SDA_READ            ; Read from display, it only provides an SDA pin"
      - "-D TFT_INVERT_COLORS=0"
      - "-D TFT_INVERSION_ON"
      - "-D TOUCH_SDA=4"
      - "-D TOUCH_SCL=0"
      - "-D TOUCH_RST=-1"
      - "-D TOUCH_IRQ=-1"
      #- "-D TOUCH_CS=12  ; Default for TFT connector"
      #- "-D TOUCH_CAL_DATA=268,3553,383,3532,6  ; Touch Calibration Data"
      - "-D SPI_FREQUENCY=80000000"
      #- "-D SPI_TOUCH_FREQUENCY=2500000"
      - "-D SPI_READ_FREQUENCY=6000000"
      - "-D TFT_RGB_ORDER=TFT_BGR ; Colour order Blue-Green-Red"
    board_build.f_flash: 80000000L

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

  # Enable fallback hotspot
  ap:
    ssid: "${dev_name} Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

# For capacitive screens
i2c:
  sda: 4
  scl: 0
  id: bus_a
  scan: true

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable over-the-air updates
ota:
  password: !secret esphome_ota_password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

custom_component:
  - lambda: |-
      auto lvgl_component = new LvglComponent();
      return {lvgl_component};

binary_sensor:
  - platform: custom
    lambda: |-
      auto sensor = new LvglIdleSensor();
      App.register_component(sensor);
      return {sensor};
    binary_sensors:
      id: lvgl_idle_sensor
      name: ${dev_name} Idle Sensor
      on_press:
        then:
          - light.turn_off: backlight
      on_release:
        then:
          - light.turn_on: backlight


light:
  # Backlight
  - platform: monochromatic
    id: backlight
    output: backlight_led
    name: ${dev_name} Backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 200ms

  # Moodlight
  - platform: rgb
    name: ${dev_name} Moodlight
    red: moodlight_red
    green: moodlight_green
    blue: moodlight_blue

output:

  # Backlight Channel
  - platform: ledc
    id: backlight_led
    pin: GPIO5

  # Moodlight color channels
  - platform: ledc
    id: moodlight_red
    pin: GPIO26
  - platform: ledc
    id: moodlight_green
    pin: GPIO32
  - platform: ledc
    id: moodlight_blue
    pin: GPIO33

number:
